version: '3.7'

services:
  ts-node-docker:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/home/node/app/src
      - ./nodemon.json:/home/node/app/nodemon.json
    container_name: articcommerce-backend
    expose:
      - '${PORT}'
    ports:
      - '${PORT}:${PORT}'
    command: npm run dev