version: '3.7'

services:
  articcommerce-api:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/home/node/app/src
      - ./nodemon.json:/home/node/app/nodemon.json
    container_name: articcommerce-backend
    expose:
      - '${PORT}'
    ports:
      - '${PORT}:${PORT}'
    depends_on:
      - db
    command: npm run dev
  db:
    container_name: postgres
    image: postgres
    ports:
      - '5433:${DB_PORT}'
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
volumes:
  db_data:
